### ISSUE TITLE
When the count finishes, an error is thrown

### ISSUE THREAD

**Issue by fishkes** [ps-cristopher/vue3-autocounter#4]
I'm using Vue 3.2.31.

I have three counters running and after they finish I get this error:

```
vue3-autocounter.esm.js:107 Uncaught (in promise) TypeError: this.currentAmount.toFixed is not a function
    at Proxy.formatedAmount (vue3-autocounter.esm.js:107:45)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at ComputedRefImpl.get value [as value] (reactivity.esm-bundler.js:1101:39)
    at Object.get [as formatedAmount] (runtime-core.esm-bundler.js:2845:30)
    at Object.get (runtime-core.esm-bundler.js:6683:32)
    at Proxy.displayedAmount (vue3-autocounter.esm.js:102:36)
    at ReactiveEffect.run (reactivity.esm-bundler.js:167:25)
    at ComputedRefImpl.get value [as value] (reactivity.esm-bundler.js:1101:39)
    at Object.get [as displayedAmount] (runtime-core.esm-bundler.js:2845:30)
    at Object.get (runtime-core.esm-bundler.js:6683:32)
```

**Comment by riztaha** [comment]
I also had this issue. This is because somewhere you're number is being read as a string. Are you using typescript? Try setting the type to Number or at the end you can force a string to number conversion in the props binded as:

`<vue3-autocounter
ref="counter"
:startAmount="0"
:endAmount="Number(10)"
:duration="1"
/>`

**Comment by ps-cristopher** [comment]
Thanks for your help @riztaha, you explained it well!. As @riztaha mentioned, it's needed to ensure that you are using actual numbers in the duration properties instead of numbers as strings. I'll close this issue.

@fishkes Here you can find the complete properties docs: https://vue3autocounter.cristopherps.dev/docs#properties
